### ISSUE TITLE
Create Step-by-Step Demo Showing How to use the `gitea` package

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gitea-demo#3]
We have got a _working_ implementation of the `gogs` interface: https://github.com/dwyl/gogs 📦 🚀 🎉 
(_works on `localhost` and **`Mock`** tests all pass on `CI`: [gogs/actions/workflows/ci](https://github.com/dwyl/gogs/actions/workflows/ci.yml) ... but it's still tedious to setup ..._) ⌛ 🙄 

We need a step-by-step example/demo **`Phoenix`** App that shows _exactly_ how to get it all working!

# Todo

Create a tutorial Rich Text Editor that saves data to https://gogs-server.fly.dev/ via `gitea` > see: https://github.com/dwyl/gitea-demo/issues/12
+ [x] Document all the steps to set up including the SSH key for `Gitea.push`
+ [x] No need for a Database or Authentication; leave it totally open but only allow editing the `README.md`
> We can get fancy _later_! This one is very deliberatly simple!
+ [x] Create new Fly.io Org: https://fly.io/dashboard/gitea-536
+ [x] Deploy it!! ~~dwyl/gogs-demo#3~~  > [dwyl/gitea-demo#6-**deploy-to-flyio**](https://github.com/dwyl/gitea-demo#6-deploy-to-flyio-)

**Comment by nelsonic** [comment]
Going to try and get this done _now_ as we need it! 🧑‍💻

**Comment by nelsonic** [comment]
"Paint" logo: 
![gogs-demo-logo](https://user-images.githubusercontent.com/194400/167251193-e0cb2874-88f0-4a78-a752-1a0f9d253e10.png)

😉

**Comment by nelsonic** [comment]
Working on `localhost`:
![image](https://user-images.githubusercontent.com/194400/167685396-207cc12f-d722-4ca3-8582-f7563597bcff.png)

**Comment by nelsonic** [comment]
Rendered markdown:
![image](https://user-images.githubusercontent.com/194400/168069048-15dd5b50-235c-4cbe-9f3e-fb306933e17c.png)

**Comment by nelsonic** [comment]
No point extending the `gogs-demo` ... transferring this to `gitea-demo` ...

**Comment by nelsonic** [comment]
Got a more real-world `gitea-demo` working on `localhost`:
![gitea-demo-homepage-updated](https://user-images.githubusercontent.com/194400/169066384-7f27971b-72ae-4adb-9c4a-2c94dfeaf086.png)

Repo updated by `Elixir/Phoenix` App: https://gitea-server.fly.dev/demo-org/hello-world
![gitea-repo-updaetd](https://user-images.githubusercontent.com/194400/169067021-cec66968-6ef7-4287-94e9-adb59ceb9f28.png)

Going to PR this update once I've added to the docs.

**Comment by nelsonic** [comment]
First I'm going to try and _deploy it_ to Fly and document the `rsa` (`ssh`) key setup.

**Comment by nelsonic** [comment]
Highlighted the timestamp for clarity:
![gitea-demo-homepage-updated](https://user-images.githubusercontent.com/194400/169069757-754dc222-fc0d-47a7-83dd-0889bfbe7b8d.png)

 https://gitea-server.fly.dev/demo-org/hello-world
![gitea-repo-updaetd](https://user-images.githubusercontent.com/194400/169069920-37014556-2291-482a-bde3-3119bccd3db3.png)

**Comment by nelsonic** [comment]
At present the `Dockerfile` has the following lines:

```sh
RUN chown nobody:nobody /app

USER nobody:nobody
```

https://github.com/dwyl/gitea-demo/blob/ce61e595361311d46c6c7798ce04b059fba56c45/Dockerfile#L65-L67

I don't understand _why_ ... 
Ok. scratch that. it's principal of least privilege: https://en.wikipedia.org/wiki/Principle_of_least_privilege
not going to escalate it to `root`. 👍

**Comment by nelsonic** [comment]
Having a bit of a hurdle deploying right now ...

```
==> Verifying app config
--> Verified app config
==> Building image
Error failed to fetch an image or build from source: error connecting to docker: failed building options: failed probing "gitea-536": context deadline exceeded
```
Investigating why ... 🔍 ⏳

**Comment by nelsonic** [comment]
Searched for:
```sh
Fly.io Error failed to fetch an image or build from source: error connecting to docker: failed building options: failed probing  context deadline exceeded
```

Found: https://community.fly.io/t/deployments-not-working-error-connecting-to-docker/3992/2
Tried:
```sh
fly auth login
```

Followed by:

```sh
LOG_LEVEL=debug fly deploy
```

Output:

```sh
==> Building image
DEBUG trying local docker daemon
DEBUG Local docker daemon unavailable
DEBUG trying remote docker daemon
DEBUG Trying 'Buildpacks' strategy
DEBUG no buildpack builder configured, skipping
DEBUG result image:<nil> error:<nil>
DEBUG Trying 'Dockerfile' strategy
DEBUG --> POST https://api.fly.io/graphql {{"query":"mutation($input: EnsureMachineRemoteBuilderInput!) { ensureMachineRemoteBuilder(input: $input) { machine { id state ips { nodes { family kind ip } } }, app { name organization { id slug } } } }","variables":{"input":{"appName":"gitea-demo","organizationId":null}}}
}
DEBUG <-- 200 https://api.fly.io/graphql (563.62ms) {"data":{"ensureMachineRemoteBuilder":{"machine":{"id":"3049c591","state":"started","ips":{"nodes":[{"family":"v6","kind":"privatenet","ip":"fdaa:0:6457:a7b:276d:0:fac1:2"},{"family":"v6","kind":"public","ip":"2605:4c40:94:ad04::fac1:3"},{"family":"v4","kind":"private","ip":"172.19.19.26"}]}},"app":{"name":"fly-builder-withered-dream-5409","organization":{"id":"0wqD28AMRNq3jtMxM5b6m9yb6oTNKk","slug":"gitea-536"}}}}}
DEBUG checking ip &{Family:v6 Kind:privatenet IP:fdaa:0:6457:a7b:276d:0:fac1:2 MaskSize:0}
Waiting for remote builder fly-builder-withered-dream-5409... ⣾ DEBUG --> POST https://api.fly.io/graphql {{"query":"query ($appName: String!) { app(name: $appName) { id name hostname deployed status version appUrl platformVersion currentRelease { evaluationId status inProgress version } config { definition } organization { id slug } services { description protocol internalPort ports { port handlers } } ipAddresses { nodes { id address type createdAt } } imageDetails { repository version } machines{ nodes { id name config state region createdAt app { name } ips { nodes { family kind ip maskSize } } host { id } } } postgresAppRole: role { name } } }","variables":{"appName":"gitea-demo"}}
}
Waiting for remote builder fly-builder-withered-dream-5409... ⣽ DEBUG <-- 200 https://api.fly.io/graphql (369.48ms) {"data":{"app":{"id":"gitea-demo","name":"gitea-demo","hostname":"gitea-demo.fly.dev","deployed":true,"version":4,"appUrl":"https://37.16.15.22","platformVersion":"nomad","currentRelease":{"evaluationId":null,"status":"succeeded","inProgress":false,"version":4},"config":{"definition":{"kill_timeout":5,"kill_signal":"SIGTERM","processes":[],"experimental":{"allowed_public_ports":[],"entrypoint":[],"cmd":[],"exec":[],"auto_rollback":true},"services":[{"processes":["app"],"protocol":"tcp","internal_port":4000,"concurrency":{"soft_limit":20,"hard_limit":25,"type":"connections"},"ports":[{"port":80,"handlers":["http"]},{"port":443,"handlers":["tls","http"]}],"tcp_checks":[{"interval":"15s","timeout":"2s","grace_period":"1s","restart_limit":0}],"http_checks":[],"script_checks":[]}],"env":{"LOG_LEVEL":"debug","PHX_HOST":"gitea-demo.fly.dev","PORT":"4000"}}},"organization":{"id":"0wqD28AMRNq3jtMxM5b6m9yb6oTNKk","slug":"gitea-536"},"services":[{"description":"TCP 80/443 ⇢ 4000","protocol":"TCP","internalPort":4000,"ports":[{"port":80,"handlers":["HTTP"]},{"port":443,"handlers":["TLS","HTTP"]}]}],"imageDetails":{"repository":"gitea-demo","version":null},"postgresAppRole":null,"ipAddresses":{"nodes":[{"id":"m86mRVKR5bBk7FxRzYgy90xly9HJ8zyYB","address":"37.16.15.22","type":"v4","createdAt":"2022-05-17T12:01:56Z"},{"id":"89D45zK5yOwYBTBlQR6ZoVBzZouvG2q9B","address":"2a09:8280:1::3c36","type":"v6","createdAt":"2022-05-17T12:01:57Z"}]},"machines":{"nodes":[]},"status":"running"}}}
DEBUG --> POST https://api.fly.io/graphql {{"query":"mutation($input: ValidateWireGuardPeersInput!) { validateWireGuardPeers(input: $input) { invalidPeerIps } }","variables":{"input":{"peerIps":["fdaa:0:6457:a7b:9476:0:a:102","fdaa:0:5a9b:a7b:dc6:0:a:102","fdaa:0:5cce:a7b:dc6:0:a:2"]}}}
}
Waiting for remote builder fly-builder-withered-dream-5409... ⣻ DEBUG <-- 200 https://api.fly.io/graphql (139.86ms) {"data":{"validateWireGuardPeers":{"invalidPeerIps":[]}}}
DEBUG result image:<nil> error:error connecting to docker: failed building options: failed probing "gitea-536": context deadline exceeded
Error failed to fetch an image or build from source: error connecting to docker: failed building options: failed probing "gitea-536": context deadline exceeded
```
Still the same error:
Continuing search. 🔍

**Comment by nelsonic** [comment]
Nuked the builder instance:

```sh
fly destroy fly-builder-withered-dream-5409
```
as per: https://community.fly.io/t/deployments-not-working-error-connecting-to-docker/3992/53

no effect.

```sh
fly destroy fly-builder-withered-dream-5409
Destroying an app is not reversible.
? Destroy app fly-builder-withered-dream-5409? Yes
Destroyed app fly-builder-withered-dream-5409
n@MBP gitea-demo % LOG_LEVEL=debug fly deploy --verbose
DEBUG Loaded flyctl config from/Users/n/.fly/config.yml
DEBUG determined hostname: "MBP"
DEBUG determined working directory: "/Users/n/code/gitea-demo"
DEBUG determined user home directory: "/Users/n"
DEBUG determined config directory: "/Users/n/.fly"
DEBUG ensured config directory exists.
DEBUG ensured config directory perms.
DEBUG cache loaded.
DEBUG config initialized.
DEBUG initialized task manager.
DEBUG skipped querying for new release
DEBUG client initialized.
DEBUG app config loaded from /Users/n/code/gitea-demo/fly.toml
==> Verifying app config
--> Verified app config
==> Building image
DEBUG trying local docker daemon
DEBUG Local docker daemon unavailable
DEBUG trying remote docker daemon
DEBUG Trying 'Buildpacks' strategy
DEBUG no buildpack builder configured, skipping
DEBUG result image:<nil> error:<nil>
DEBUG Trying 'Dockerfile' strategy
DEBUG --> POST https://api.fly.io/graphql {{"query":"mutation($input: EnsureMachineRemoteBuilderInput!) { ensureMachineRemoteBuilder(input: $input) { machine { id state ips { nodes { family kind ip } } }, app { name organization { id slug } } } }","variables":{"input":{"appName":"gitea-demo","organizationId":null}}}
}
DEBUG <-- 200 https://api.fly.io/graphql (6.7s) {"data":{"ensureMachineRemoteBuilder":{"machine":{"id":"4369c122","state":"starting","ips":{"nodes":[{"family":"v6","kind":"privatenet","ip":"fdaa:0:6457:a7b:276d:0:fce6:2"},{"family":"v6","kind":"public","ip":"2605:4c40:94:ad04::fce6:3"},{"family":"v4","kind":"private","ip":"172.19.19.26"}]}},"app":{"name":"fly-builder-withered-field-1979","organization":{"id":"0wqD28AMRNq3jtMxM5b6m9yb6oTNKk","slug":"gitea-536"}}}}}
DEBUG checking ip &{Family:v6 Kind:privatenet IP:fdaa:0:6457:a7b:276d:0:fce6:2 MaskSize:0}
Waiting for remote builder fly-builder-withered-field-1979... ⣾ DEBUG --> POST https://api.fly.io/graphql {{"query":"query ($appName: String!) { app(name: $appName) { id name hostname deployed status version appUrl platformVersion currentRelease { evaluationId status inProgress version } config { definition } organization { id slug } services { description protocol internalPort ports { port handlers } } ipAddresses { nodes { id address type createdAt } } imageDetails { repository version } machines{ nodes { id name config state region createdAt app { name } ips { nodes { family kind ip maskSize } } host { id } } } postgresAppRole: role { name } } }","variables":{"appName":"gitea-demo"}}
}
Waiting for remote builder fly-builder-withered-field-1979... ⣽ DEBUG <-- 200 https://api.fly.io/graphql (355.31ms) {"data":{"app":{"id":"gitea-demo","name":"gitea-demo","hostname":"gitea-demo.fly.dev","deployed":true,"version":4,"appUrl":"https://37.16.15.22","platformVersion":"nomad","currentRelease":{"evaluationId":null,"status":"succeeded","inProgress":false,"version":4},"config":{"definition":{"kill_timeout":5,"kill_signal":"SIGTERM","processes":[],"experimental":{"allowed_public_ports":[],"entrypoint":[],"cmd":[],"exec":[],"auto_rollback":true},"services":[{"processes":["app"],"protocol":"tcp","internal_port":4000,"concurrency":{"soft_limit":20,"hard_limit":25,"type":"connections"},"ports":[{"port":80,"handlers":["http"]},{"port":443,"handlers":["tls","http"]}],"tcp_checks":[{"interval":"15s","timeout":"2s","grace_period":"1s","restart_limit":0}],"http_checks":[],"script_checks":[]}],"env":{"LOG_LEVEL":"debug","PHX_HOST":"gitea-demo.fly.dev","PORT":"4000"}}},"organization":{"id":"0wqD28AMRNq3jtMxM5b6m9yb6oTNKk","slug":"gitea-536"},"services":[{"description":"TCP 80/443 ⇢ 4000","protocol":"TCP","internalPort":4000,"ports":[{"port":80,"handlers":["HTTP"]},{"port":443,"handlers":["TLS","HTTP"]}]}],"imageDetails":{"repository":"gitea-demo","version":null},"postgresAppRole":null,"ipAddresses":{"nodes":[{"id":"m86mRVKR5bBk7FxRzYgy90xly9HJ8zyYB","address":"37.16.15.22","type":"v4","createdAt":"2022-05-17T12:01:56Z"},{"id":"89D45zK5yOwYBTBlQR6ZoVBzZouvG2q9B","address":"2a09:8280:1::3c36","type":"v6","createdAt":"2022-05-17T12:01:57Z"}]},"machines":{"nodes":[]},"status":"running"}}}
DEBUG --> POST https://api.fly.io/graphql {{"query":"mutation($input: ValidateWireGuardPeersInput!) { validateWireGuardPeers(input: $input) { invalidPeerIps } }","variables":{"input":{"peerIps":["fdaa:0:5cce:a7b:dc6:0:a:2","fdaa:0:6457:a7b:9476:0:a:102","fdaa:0:3800:a7b:9476:0:a:2","fdaa:0:5a9b:a7b:dc6:0:a:102"]}}}
}
DEBUG <-- 200 https://api.fly.io/graphql (143.92ms) {"data":{"validateWireGuardPeers":{"invalidPeerIps":[]}}}
DEBUG result image:<nil> error:error connecting to docker: failed building options: failed probing "gitea-536": context deadline exceeded
Error failed to fetch an image or build from source: error connecting to docker: failed building options: failed probing "gitea-536": context deadline exceeded
```

**Comment by nelsonic** [comment]
https://status.flyio.net/
![image](https://user-images.githubusercontent.com/194400/169088495-853a62d8-2162-4bfd-bbd4-563487520239.png)


https://status.flyio.net/incidents/m14bszg6y6m3
![image](https://user-images.githubusercontent.com/194400/169088329-7100c700-4504-4b9a-9a1c-ce77c8f9f1cc.png)

hmm ...

**Comment by nelsonic** [comment]
Tried `fly wireguard websockets enable` as per https://community.fly.io/t/deployments-not-working-error-connecting-to-docker/3992/58
But still have the same error.

**Comment by nelsonic** [comment]
Kept scrolling ... last answer in the thread is: https://community.fly.io/t/deployments-not-working-error-connecting-to-docker/3992/60
```sh
fly wireguard list
fly wireguard reset
fly wireguard remove
```
Appears to have worked!!

```sh
...
DEBUG <-- 200 https://api.fly.io/graphql (181.77ms) {"data":{"app":{"deploymentStatus":{"id":"8184850e-46c5-45d9-ce03-7ccc0c517f26","inProgress":false,"status":"successful","successful":true,"description":"Deployment completed successfully","version":5,"desiredCount":1,"placedCount":1,"healthyCount":1,"unhealthyCount":0,"allocations":[{"id":"f5af7de3-f5a3-a25f-af5f-0ceb19fd9b89","idShort":"f5af7de3"," 1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
--> v5 deployed successfully
```

**Comment by nelsonic** [comment]
```sh
2022-05-18T15:31:33Z app[af04c025] lhr [info]    ** (ErlangError) Erlang error: :enoent
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (elixir 1.12.1) lib/system.ex:1041: System.cmd("git", ["clone", "git@gitea-server.fly.dev:demo-org/hello-world.git", "/app/demo-org/hello-world"], [stderr_to_stdout: true])
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (git_cli 0.3.0) lib/git.ex:105: Git.execute_command/4
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (gitea 1.0.2) lib/gitea.ex:155: Gitea.clone/1
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:15: AppWeb.PageController.index/2
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.action/2
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.phoenix_controller_pipeline/2
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (phoenix 1.6.9) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
2022-05-18T15:31:33Z app[af04c025] lhr [info]        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
```

**Comment by SimonLab** [comment]
If I remember correctly this latest error :arrow_up: was due to `git` not being installed on Fly.
Updating the Dockerfile to install it:

```Dockerfile
FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git nodejs npm \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*
```
Hope this solve/help this issue

**Comment by nelsonic** [comment]
@SimonLab I was literally just about to ask you what you did to make `git` work on Fly. Thanks! 🙏

**Comment by nelsonic** [comment]
I think Fly hates me ... 🤷‍♂️ 

```sh
Remote builder fly-builder-withered-field-1979 ready
==> Creating build context
--> Creating build context done
DEBUG fetching docker server info
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
[+] Building 37.5s (0/1)
[+] Building 1.8s (5/9)
 => CACHED [internal] load remote build context                                                                                                                                              0.0s
 => CACHED copy /context /                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/alpine:3.13.3                                                                                                                             0.7s
 => [app 1/5] FROM docker.io/library/alpine:3.13.3@sha256:826f70e0ac33e99a72cf20fb0571245a8fee52d68cb26d8bc58e53bfa65dcdfa                                                                   0.0s
 => ERROR FROM docker.io/library/build:latest                                                                                                                                                1.1s
 => => resolve docker.io/library/build:latest                                                                                                                                                1.1s
------
 > FROM docker.io/library/build:latest:
------
DEBUG result image:<nil> error:error building: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error failed to fetch an image or build from source: error building: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

"insufficient_scope: authorization failed" ... why?! 🤷‍♂️

**Comment by nelsonic** [comment]
```
DEBUG <-- 200 https://api.fly.io/graphql (170.57ms) {"data":{"app":{"deploymentStatus":{"id":"c4ac23e3-6ac6-41ed-1f76-72e4da2ec068","inProgress":false,"status":"failed","successful":false,"description":"Failed due to unhealthy allocations - rolling back to job version 8","version":9,"desiredCount":1,"placedCount":1,"healthyCount":0,"unhealthyCount":1,"allocations":[{"id":"e6b44528-0a5e 1 desired, 1 placed, 0 healthy, 1 unhealthy
--> v9 failed - Failed due to unhealthy allocations - rolling back to job version 8 and deploying as v10

--> Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

# 🙄

**Comment by nelsonic** [comment]
@SimonLab your tip got me _most_ of the way to my goal. 👌 
But after half an hour of staring at the `Dockerfile` 👀 
e.g. going through https://github.com/fly-apps/hello_elixir/blob/main/Dockerfile line-by-line 🔍 
it _eventually_ clicked that having `git` in the `BUILDER_IMAGE` wasn't _enough_. 💭 
Had to add it to the `RUNNER_IMAGE` too! (duh!) 🤦‍♂️ 
Now it works!! 🎉  
(_almost ..._)

now I'm stuck with granting the `nobody` user access to the `ssh` key file ... 🙄

**Comment by nelsonic** [comment]
Basically I'm still stuck with the `ssh key` ... I've attempted to summarise the issue in #4 💭 
Any help _very_ much appreciate. 🙏

**Comment by nelsonic** [comment]
With @SimonLab help we figured out the `ssh` key issue: https://github.com/dwyl/gitea-demo/issues/4#issuecomment-1132760741 🚀 
This is now succinctly documented in #5 (**`awaiting-revew`** 🙏 )
